name: clash_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  ffi: ^2.1.3
  dbus: ^0.7.10
  path_provider: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
